name: methods_seminar_2019_env
channels:
  - defaults
  - conda-forge
  - ostrokach-forge
  - pkgw-forge
dependencies:
  - pygobject
  - matplotlib
  - scikit-learn
  - numpy
  - pandas
  - networkx
  - graph-tool>=2.27
  - pip:
    - powerlaw
